var SkillNames = ['Learn To Moonwalk', 'Sharpen Knives', 'Whistle',
'Twirl a pen',
'Take amazing selfies',
'Be a good story teller',
'Fold clothes',
'Pick a lock',
'Tie a tie',
'Juggle',
'Speed read',
'Solve a rubiks cube',
'First aid',
'Cook',
'Mix drinks',
'Public speaking',
'Body language',
'Program',
'manage money',
'Play an instrument',
'Use Microsoft office',
'Use Photoshop',
'Videography',
'Improve memory',
'Draw',
'Paint',
'Dance',
'Plan a career',
'Mix music',
'Buy a house'
];

module.exports.SkillNames = SkillNames;